### ISSUE TITLE
Update Atmosphere page

### ISSUE THREAD

**Issue by dandv** [MeteorPackaging/nvd3#1]
Per https://github.com/MeteorPackaging/autopublish.meteor.com/wiki#users-and-organizations step 3

Example: https://atmospherejs.com/webix

**Comment by bobiblazeski** [comment]
@dandv  Why I can't edit nvd3 organization description ? 
Exception while simulating the effect of invoking 'updateProfile' r Error: Unauthorized [403]

**Comment by splendido** [comment]
I guess you should add yourself among the people belonging to the organization.
If you're already in, it's a bug!

**Comment by bobiblazeski** [comment]
I'm already member 
![image](https://cloud.githubusercontent.com/assets/2140890/6229809/c6f79f90-b6ba-11e4-8751-30086028901e.png)

**Comment by splendido** [comment]
And on atmosphere you're logged in with your Meteor Developer Account?

Lets see on the [atmosphere issue](https://github.com/percolatestudio/atmosphere/issues) whether there's something similar around..

Otherwise file a new issue!

**Comment by bobiblazeski** [comment]
Updated https://atmospherejs.com/nvd3 
![members](https://cloud.githubusercontent.com/assets/2140890/6237937/56d66146-b6f7-11e4-9eed-f5d634160bef.png)

**Comment by splendido** [comment]
:+1:

**Comment by dandv** [comment]
LGTM
