### ISSUE TITLE
Deleting novus profile

### ISSUE THREAD

**Issue by bobiblazeski** [MeteorPackaging/nvd3#5]
@dandv  I created meteor developer profile by mistake  for novus, how can I delete it?

**Comment by splendido** [comment]
You should ask Nick Martin (github username: n1mmy) or Emily Stark (estark37) from MDG.
The can delete it manually, as long as there's no packages published by that user.

**Comment by dandv** [comment]
Yes, pinging @estark37 to delete https://atmospherejs.com/novus.

**Comment by splendido** [comment]
...last time I wrote an email to Emily I got a reply from Nick ;-)

Btw @bobiblazeski, couldn't you tell the password for `novus` to Robin Hu or some guys there so they can take ownership on it?

**Comment by bobiblazeski** [comment]
Sure email with credentials sent to  @robinfhu

**Comment by robinfhu** [comment]
We won't be needing that account for now. You may remove it.

**Comment by estark37** [comment]
Yep, I don't work at MDG anymore -- you can always email contact@meteor.com for this kind of thing (probably generally preferable to emailing core devs personally).

**Comment by gadicc** [comment]
OT, but, @estark37, wish you the best of luck in all your future endeavours.  If it's anything you can talk about, we'd love to know :)

**Comment by splendido** [comment]
Yep, I wish you all the best too Emily!
Thanks for the big contributions you made to Meteor and its community!!

Cheers,
Luca

**Comment by estark37** [comment]
Thanks @gadicc and @splendido! I'm working on the Chrome security team now.

**Comment by splendido** [comment]
Since I'm a fan of Chrome, from now on I'll sleep better nights knwing you're behind it! ;-)
Well done, keep up the good work!

**Comment by dandv** [comment]
@estark37 - welcome fellow Googler :)

**Comment by gadicc** [comment]
@estark, I echo @splendido's words, would have said the same exactly :>  Congratulations and we wish you all the best there.

**Comment by bobiblazeski** [comment]
Got word from meteor, they prefer to keep the account dormant.

**Comment by splendido** [comment]
...the fact that there is no way to delete users nor packages is a bit weird! :-(

But we'll have to live with it until MDG will consider the topic...

**Comment by dandv** [comment]
The only success I've had to MDG and MD accounts was to convert a user to an organization. Other than that, not even sending a message to the owner of a username was possible.

For example, I want to publish a simple package to add a "Fork me on GitHub" badge. It should be under the `github` org. But that username is taken, and we [don't know anything about it](https://atmospherejs.com/github).
